spring:
  application:
    name: image-converter-api

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

aws:
  region: ${AWS_REGION}
  s3:
    bucket:

